### ISSUE TITLE
Fix commit pannel template loading

### ISSUE THREAD

**Issue by CyberGear** [TeleSoftas/git-config-commit-template-ij-plugin#11]
Change loading to prefer manual refresh over automatic replacement when text is present in the message box
use reload button near the history button

**Comment by first-qiuming** [comment]
commit message 加载模板内容时，会出现中文乱码

**Comment by CyberGear** [comment]
@first-qiuming Could You give screenshots? What is happening? And what is expected?

google translate:
能给个截图吗？ 怎么了？ 什么是预期的？
